language: node_js
deploy:
  provider: npm
  email: "chris@chrisdoingweb.com"
  api_key:
    secure: "XKWOli+/hAxdV/m/W2AWM6KgkmYJcGswTQulT/lPovNVqAX2jJB8twwSFRB7rYRM6JT618Qggql9HTV84KsR00gaKa1VDLnR9YSQWjrA+gShVN5j7/eZGm7At73+E3u1Z5B9Xmq6+/S2+W0nBiF3XKLbV6t6B0h80EyPgAkWxcodrLSoMU4HN+nQ1F18Gl9MnKdqaCj23bzVHwNefB0p6CF+gmWuqKghiAquRfzSgmySMndCDk7zYFZ+zc1ivHIZ94Mm3gVloa6zxcS4jVHeLmFqKx1ZpWoepY+omvBmCEvMXNuUF87ZZo5eOuqF0aJEust0EFGwdtYSb2zm2h7IGvOkl/ZqhPMcFWsvuQDH9SlcTPvpEjtrH8aho5wtYAc0xg9pojFs8eJEHWX2JmuFPcxFBx9ru17bnh1Zx4CNYG6Rt17xPVqw9R6rzytjc5av2RmFKpdbGMkI8e0lsY8i/y8tTvOLx7Wii7JaMF7vw19HCmphQvh3h22VTWVVlC3vMEH11Jv5IO7R0YNI785cj5O5+C26MmFcjli9lFVcBuentJG07rFtuFyuDlK9EwgO2ItWrtxpfEmeDEkpAafNwtsydUrdC7ZV05fJMFS78ZW8s85CvxZEPaOHGuy8YIel0n+JEo/ya9YKcFHt9FGMQh2UjjV8eSWy7R3RAiN5hAU="
