language: node_js
deploy:
  provider: npm
  email: "chris@chrisdoingweb.com"
  api_key:
    secure: "nSsEZ9tVuz2rzhRpCVVmYrHi82Njr7VeoMpwHKdmga1WwLy+dBGPaPr3CkimjHuxP2EIOT2QNan/0uBhqzZ9YpWn0qRQx1iIbYT/Txyhl4FvALVnF7HX4XYe13TTlPEZR1pNVDGO64V27mxi+0QjNepzLUWuEhm3cz/enVerJZFbg+kW9QQgPXvsmjUOvKCfMYhkUGR0j0rEt8zzGVB1+XtoUIykpfFkSAaa/siAEtb1XuVbAHjf1v4OiiQJ0qO/gAK1qsBbm6fTpPUeWlZd0YiozAr3mbBLcOAXiSkHByRj5mbSogVBN2PcqPwzJ9JrFRRsCPTPUwkMdL2xyNB8YmbFhX4Xfvde6f+q1N2VGiLzZD9WjzHmESbyQJeGK+0hXasxDPnCvOxUCA3rFmOcBzPVAD5QQ1S/QyzxJrXA9dsEuHp3E3UTju2f0PVSHPJGbSCxU3P/y5jz/4q2ea6AxXS2zz+WzVA9zCjUZEKZIlor2AxD3somZA7HL8QgKJcF+6B5pgYt3zNH4Lg9yXScFWdKHSUByOb7HgdzrDCAE+mpgb9I5/WaD21IQZ4AdkijT104soAfmReIpBkx/6azTei6ZQpyE+n+6Rj4pSUeJZ+lIhMk8NlpE1wXcq+kflYC+YfKWXAOgljiapt+3WMsjcMkH3mWzbmhwPfTlIzdeRk="
